name: Cypress E2E

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC-SANITY_POJECT_ID }}
        NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
        AUTH_SECRET=: ${{ secrets.AUTH_SECRET }}

        AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
        AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}

        SANITY_EDIT_TOKEN: ${{ secrets.SANITY_EDIT_TOKEN }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20.9.0
            cache: npm


      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Start Next.js
        run: npm run start &

      - name: Wait for app
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: npm run test:e2e