name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build

      # Zaženi Next.js server v ozadju
      - run: npm start &
      - run: npx wait-on http://localhost:3000

      # Pognaj Cypress E2E teste
      - run: npm run test:e2e

      # Pognaj Cypress component teste
      - run: npm run test:component
